name: pendeteksi_cuaca
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  camera: ^0.10.5+9
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/weather_int8.tflite
